### ISSUE TITLE
0.1.2加载报错

### ISSUE THREAD

**Issue by kogekiplay** [MrXiaoM/WifeYouWant#2]
抽老婆: java.lang.IllegalArgumentException: Element with name 'enable-groups' is already registered
java.lang.IllegalArgumentException: Element with name 'enable-groups' is already registered
	at kotlinx.serialization.descriptors.ClassSerialDescriptorBuilder.element(SerialDescriptors.kt:281)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1$descriptor$2$1.invoke(PluginDataImpl.kt:52)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1$descriptor$2$1.invoke(PluginDataImpl.kt:50)
	at kotlinx.serialization.descriptors.SerialDescriptorsKt.buildClassSerialDescriptor(SerialDescriptors.kt:58)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1$descriptor$2.invoke(PluginDataImpl.kt:50)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1$descriptor$2.invoke(PluginDataImpl.kt:48)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.getDescriptor(PluginDataImpl.kt:48)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:59)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47)
	at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:44)
	at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:59)
	at WifeYouWant-0.1.2.mirai2.jar//top.mrxiaom.WifeYouWant.onEnable(WifeYouWant.kt:33)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:278)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:178)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:235)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
	at org.itxtech.mcl.Loader.start(Loader.java:189)
	at org.itxtech.mcl.Loader.main(Loader.java:79)

**Comment by MrXiaoM** [comment]
好，[https://github.com/MrXiaoM/WifeYouWant/releases/tag/0.1.2-fix1](复制粘贴忘改了)
